// Sample data extracted from IAS-Budget Utilization.xlsx
export const sampleBudgetSummary = {
  current: {
  "program": "Building Internationalization Competitiveness Program for Philippine Higher Education",
  "pap": "BICPPHE",
  "allotment": {
    "central": 137590547.9,
    "regional": 0,
    "total": 137590547.9
  },
  "obligation": {
    "central": 25190537.88,
    "regional": 0,
    "total": 25190537.88,
    "percent": 0.1830833459
  },
  "disbursement": {
    "central": 4852905.74,
    "regional": 0,
    "total": 4852905.74,
    "percent": 0.1926479602
  },
  "unobligated": {
    "central": 112400010,
    "regional": 0,
    "total": 112400010,
    "percent": 0.8169166541
  },
  "unpaid": {
    "central": 20337632.14,
    "regional": 0,
    "total": 20337632.14,
    "percent": 0.8073520398
  }
},
  continuing: {
  "program": "Building Internationalization Competitiveness Program for Philippine Higher Education",
  "pap": "BICPPHE",
  "allotment": {
    "central": 2395831.23,
    "regional": 236433,
    "total": 2632264.23
  },
  "obligation": {
    "central": 2395831.23,
    "regional": 58589,
    "total": 2454420.23,
    "percent": 0.9324368739
  },
  "disbursement": {
    "central": 2220938.56,
    "regional": 58589,
    "total": 2279527.56,
    "percent": 0.9287437954
  },
  "unobligated": {
    "central": 0,
    "regional": 177844,
    "total": 177844,
    "percent": 0.06756312606
  },
  "unpaid": {
    "central": 174892.67,
    "regional": 0,
    "total": 174892.67,
    "percent": 0.07125620457
  }
}
};

export const sampleBudgetTransactions = [
  {
    "id": 1,
    "obligationNumber": "03-104-369-2026-02-00035 Continuing",
    "pap": "BICPPHE",
    "payee": "ARMIE O. BUNAG",
    "particulars": "COS' Salaries - January 5 - March 31, 2026 - PTS III",
    "obligationDate": "Feb 9, 2026",
    "obligationAmount": 185411.69,
    "disbursementDate": "Feb 20, 2026",
    "disbursementAmount": 179597.69,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CONTINUING"
  },
  {
    "id": 2,
    "obligationNumber": "03-104-369-2026-02-00036 Continuing",
    "pap": "BICPPHE",
    "payee": "PAULINE C. REYES",
    "particulars": "COS' Salaries - January 5 - March 31, 2026 - PTS III",
    "obligationDate": "Feb 9, 2026",
    "obligationAmount": 185411.69,
    "disbursementDate": "Feb 20, 2026",
    "disbursementAmount": 183153.41,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CONTINUING"
  },
  {
    "id": 3,
    "obligationNumber": "03-104-369-2026-02-00037 Continuing",
    "pap": "BICPPHE",
    "payee": "JOSHUA KEN J. POLICARPIO",
    "particulars": "COS' Salaries - January 5 - March 31, 2026 - PTS III",
    "obligationDate": "Feb 9, 2026",
    "obligationAmount": 185411.69,
    "disbursementDate": "Feb 20, 2026",
    "disbursementAmount": 180687.04,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CONTINUING"
  },
  {
    "id": 4,
    "obligationNumber": "03-104-369-2026-02-00038 Continuing",
    "pap": "BICPPHE",
    "payee": "MARICEL N. ERMITA",
    "particulars": "COS' Salaries - January 5 - March 31, 2026 - PTS II",
    "obligationDate": "Feb 9, 2026",
    "obligationAmount": 145310.01,
    "disbursementDate": "Feb 20, 2026",
    "disbursementAmount": 95474.85,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CONTINUING"
  },
  {
    "id": 5,
    "obligationNumber": "03-104-369-2026-02-00039 Continuing",
    "pap": "BICPPHE",
    "payee": "ELDRIN DELGADO",
    "particulars": "COS' Salaries - January 5 - March 31, 2026 - PTS II",
    "obligationDate": "Feb 9, 2026",
    "obligationAmount": 145310.01,
    "disbursementDate": "Feb 20, 2026",
    "disbursementAmount": 131385.48,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CONTINUING"
  },
  {
    "id": 6,
    "obligationNumber": "03-104-369-2026-02-00040 Continuing",
    "pap": "BICPPHE",
    "payee": "DANNA MARIE H. SISTER",
    "particulars": "COS' Salaries - January 5 - March 31, 2026 - PTS II",
    "obligationDate": "Feb 9, 2026",
    "obligationAmount": 145310.01,
    "disbursementDate": "Feb 20, 2026",
    "disbursementAmount": 145223.79,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CONTINUING"
  },
  {
    "id": 7,
    "obligationNumber": "03-104-369-2026-02-00041 Continuing",
    "pap": "BICPPHE",
    "payee": "NINO SATHUR FIRME",
    "particulars": "COS' Salaries - January 5 - March 31, 2026 - PTS II",
    "obligationDate": "Feb 9, 2026",
    "obligationAmount": 145310.01,
    "disbursementDate": "Feb 20, 2026",
    "disbursementAmount": 139217.13,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CONTINUING"
  },
  {
    "id": 8,
    "obligationNumber": "03-104-369-2026-02-00042 Continuing",
    "pap": "BICPPHE",
    "payee": "PRINCE MICHAEL B. FUENTES",
    "particulars": "COS' Salaries - January 7 - March 31, 2026 - PTS II",
    "obligationDate": "Feb 9, 2026",
    "obligationAmount": 142044.62,
    "disbursementDate": "Feb 20, 2026",
    "disbursementAmount": 134325.91,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CONTINUING"
  },
  {
    "id": 9,
    "obligationNumber": "03-104-369-2026-02-00043 Continuing",
    "pap": "BICPPHE",
    "payee": "NERISSA MARIE H. GONO CRUZ",
    "particulars": "COS' Salaries - January 5 - March 31, 2026 - PTS II",
    "obligationDate": "Feb 9, 2026",
    "obligationAmount": 145310.01,
    "disbursementDate": "Feb 20, 2026",
    "disbursementAmount": 134508.56,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CONTINUING"
  },
  {
    "id": 10,
    "obligationNumber": "03-104-369-2026-02-00044 Continuing",
    "pap": "BICPPHE",
    "payee": "JAVEE A. TENORIA",
    "particulars": "COS' Salaries - January 5 - March 31, 2026 - PTS I",
    "obligationDate": "Feb 9, 2026",
    "obligationAmount": 116952.89,
    "disbursementDate": "Feb 20, 2026",
    "disbursementAmount": 115100.08,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CONTINUING"
  },
  {
    "id": 11,
    "obligationNumber": "03-104-369-2026-02-00045 Continuing",
    "pap": "BICPPHE",
    "payee": "ARCHANGEL O. ABELEDA",
    "particulars": "COS' Salaries - January 5 - March 31, 2026 - PTS I",
    "obligationDate": "Feb 9, 2026",
    "obligationAmount": 116952.89,
    "disbursementDate": "Feb 20, 2026",
    "disbursementAmount": 72510.89,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CONTINUING"
  },
  {
    "id": 12,
    "obligationNumber": "03-104-369-2026-02-00046 Continuing",
    "pap": "BICPPHE",
    "payee": "SHERIE ANN N. CABANA",
    "particulars": "COS' Salaries - January 5 - March 31, 2026 - PTS I",
    "obligationDate": "Feb 9, 2026",
    "obligationAmount": 116952.89,
    "disbursementDate": "Feb 20, 2026",
    "disbursementAmount": 106191.2,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CONTINUING"
  },
  {
    "id": 13,
    "obligationNumber": "03-104-369-2026-02-00047 Continuing",
    "pap": "BICPPHE",
    "payee": "KIMBERLY O. DAYAWON",
    "particulars": "COS' Salaries - January 5 - March 31, 2026 - PTS I",
    "obligationDate": "Feb 9, 2026",
    "obligationAmount": 116952.89,
    "disbursementDate": "Feb 20, 2026",
    "disbursementAmount": 116937.44,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CONTINUING"
  },
  {
    "id": 14,
    "obligationNumber": "03-104-369-2026-02-00048 Continuing",
    "pap": "BICPPHE",
    "payee": "JULES MARIEL S. MARTIN",
    "particulars": "COS' Salaries - January 5 - March 31, 2026 - PTS I",
    "obligationDate": "Feb 9, 2026",
    "obligationAmount": 116952.89,
    "disbursementDate": "Feb 20, 2026",
    "disbursementAmount": 110529.85,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CONTINUING"
  },
  {
    "id": 15,
    "obligationNumber": "03-104-369-2026-02-00049 Continuing",
    "pap": "BICPPHE",
    "payee": "MA. SAMANTHA M. LUCIDO",
    "particulars": "COS' Salaries - January 5 - March 31, 2026 - PTS I",
    "obligationDate": "Feb 9, 2026",
    "obligationAmount": 116952.89,
    "disbursementDate": "Feb 20, 2026",
    "disbursementAmount": 116952.89,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CONTINUING"
  },
  {
    "id": 16,
    "obligationNumber": "03-104-369-2026-02-00050 Continuing",
    "pap": "BICPPHE",
    "payee": "JENNIFER P. CATUNGAL",
    "particulars": "COS' Salaries - January 5 - March 31, 2026 - PSS V",
    "obligationDate": "Feb 9, 2026",
    "obligationAmount": 92733.41,
    "disbursementDate": "Feb 20, 2026",
    "disbursementAmount": 92445.77,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CONTINUING"
  },
  {
    "id": 17,
    "obligationNumber": "03-104-369-2026-02-00051 Continuing",
    "pap": "BICPPHE",
    "payee": "JULIA D. AGAPITO",
    "particulars": "COS' Salaries - January 5 - March 31, 2026 - PSS IV",
    "obligationDate": "Feb 9, 2026",
    "obligationAmount": 83817.33,
    "disbursementDate": "Feb 18, 2026",
    "disbursementAmount": 83375.73,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CONTINUING"
  },
  {
    "id": 18,
    "obligationNumber": "03-104-369-2026-02-00104 Current",
    "pap": "BICPPHE",
    "payee": "MERALCO",
    "particulars": "Obligation for payment of Electric consumption for the period of December 25, 2025-January 24, 2026.",
    "obligationDate": "Feb 16, 2026",
    "obligationAmount": 27953.93,
    "disbursementDate": "Feb 18, 2026",
    "disbursementAmount": 27953.93,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 19,
    "obligationNumber": "03-104-369-2026-02-00105 Current",
    "pap": "BICPPHE",
    "payee": "MANILA WATER",
    "particulars": "Obligation for payment of Manila Water under Contract Account No. 17158488 for the period of December 7, 2025-January 6, 2026.",
    "obligationDate": "Feb 16, 2026",
    "obligationAmount": 2674.41,
    "disbursementDate": "Feb 18, 2026",
    "disbursementAmount": 2674.41,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 20,
    "obligationNumber": "03-104-369-2026-02-00108 Continuing",
    "pap": "BICPPHE",
    "payee": "DANIEL H. SABIANO",
    "particulars": "COS' Salaries - January 5 - March 31, 2026 - PSS V",
    "obligationDate": "Feb 18, 2026",
    "obligationAmount": 92733.41,
    "disbursementDate": "Feb 25, 2026",
    "disbursementAmount": 83320.85,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CONTINUING"
  },
  {
    "id": 21,
    "obligationNumber": "03-104-369-2026-02-00121 Current",
    "pap": "BICPPHE",
    "payee": "MANILA WATER",
    "particulars": "Obligation for payment of Manila Water under Contract Account No. 17158488 for the period of January 7-February 6, 2026.",
    "obligationDate": "Feb 19, 2026",
    "obligationAmount": 4630.08,
    "disbursementDate": "Feb 20, 2026",
    "disbursementAmount": 4630.08,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 22,
    "obligationNumber": "03-104-369-2026-02-00124 Current",
    "pap": "BICPPHE",
    "payee": "PHILIPPINE AIRLINES",
    "particulars": "Payment for the airfare expense of Dr. Christine Nabor Ferrer and Ms. Jesusa Rocel Estanislao in Third Regional Consultation Workshop on the ASEAN Work Plan on Education (AWPE) 2026-2030 in Singapore for the period of February 2-5, 2026",
    "obligationDate": "Feb 24, 2026",
    "obligationAmount": 51440,
    "disbursementDate": "Feb 26, 2026",
    "disbursementAmount": 51440,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 23,
    "obligationNumber": "03-104-369-2026-02-00126 Current",
    "pap": "BICPPHE",
    "payee": "MABEL A. GUTIERREZ",
    "particulars": "Reimbursement of travel expense incurred during the ERASMUS+ networks and the National Erasmus+Offices(NEO) Representatives, the International Contact Points(ICP) of the Erasmus+National Agencies and Erasmus+National Focal Points for the period of January 24-29,2026 in Brussels, Belgium",
    "obligationDate": "Feb 25, 2026",
    "obligationAmount": 41650.56,
    "disbursementDate": "Mar 10, 2026",
    "disbursementAmount": 41650.56,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 24,
    "obligationNumber": "03-104-369-2026-02-00127 Current",
    "pap": "BICPPHE",
    "payee": "CHRISTINE N. FERRER",
    "particulars": "Reimbursement of travel expense incurred during the Third Regional Consultation Workshop on the ASEAN Work Plan on Education (AWPE) 2026-2030 for the period of February 2-5,2026 in Singapore",
    "obligationDate": "Feb 27, 2026",
    "obligationAmount": 91964.56,
    "disbursementDate": "Mar 10, 2026",
    "disbursementAmount": 91964.56,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 25,
    "obligationNumber": "03-104-369-2026-02-00128 Current",
    "pap": "BICPPHE",
    "payee": "JESUSA ROCEL S. ESTANISLAO",
    "particulars": "Reimbursement of travel expense incurred during the Third Regional Consultation Workshop on the ASEAN Work Plan on Education (AWPE) 2026-2030 for the period of February 2-5,2026 in Singapore",
    "obligationDate": "Feb 27, 2026",
    "obligationAmount": 91964.56,
    "disbursementDate": "Mar 10, 2026",
    "disbursementAmount": 91964.56,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 26,
    "obligationNumber": "03-104-369-2026-02-00129 Current",
    "pap": "BICPPHE",
    "payee": "LANDBANK OF THE PHILIPPINES",
    "particulars": "Payment for the UMAP membership fee 2026",
    "obligationDate": "Feb 27, 2026",
    "obligationAmount": 133852.1,
    "disbursementDate": "Mar 6, 2026",
    "disbursementAmount": 133852.1,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 27,
    "obligationNumber": "03-104-369-2026-03-00131 Current",
    "pap": "BICPPHE",
    "payee": "ROGER Y. CHAO",
    "particulars": "Reimbursement of travel expense incurred during the Third Regional Consultation Workshop on the ASEAN Work Plan on Education (AWPE) 2026-2030 for the period of February 2-5,2026 in Singapore",
    "obligationDate": "Mar 2, 2026",
    "obligationAmount": 21444.96,
    "disbursementDate": "Mar 10, 2026",
    "disbursementAmount": 21444.96,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 28,
    "obligationNumber": "03-104-369-2026-03-00140 Current",
    "pap": "BICPPHE",
    "payee": "HANN PHILIPPINES, INC. (CLARK MARRIOTT HOTEL)",
    "particulars": "To obligate the amount for the procurement of food and accommodation for the conduct of the Planning and Preparatory Meeting with Education Malaysia Global Services and International Partners for the ASEAN GEMS Plus Initiative for the period of March 09-12,2026.",
    "obligationDate": "Mar 9, 2026",
    "obligationAmount": 628000,
    "disbursementDate": "Jun 3, 2026",
    "disbursementAmount": 628000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 29,
    "obligationNumber": "03-104-369-2026-03-00143 Current",
    "pap": "BICPPHE",
    "payee": "MANGELTVISTAN CORPORATION",
    "particulars": "To obligate the amount for the procurement of food and accommodation for the conduct of the Planning and Preparatory Meeting with Education Malaysia Global Services and International Partners for the ASEAN GEMS Plus Initiative for the period of March 09-12,2026.",
    "obligationDate": "Mar 9, 2026",
    "obligationAmount": 80250,
    "disbursementDate": "May 20, 2026",
    "disbursementAmount": 78726.3,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 30,
    "obligationNumber": "03-104-369-2026-03-00153 Current",
    "pap": "BICPPHE",
    "payee": "MERALCO",
    "particulars": "Payment of Electric consumption for the period of January 25,2026 to February24,2026",
    "obligationDate": "Mar 11, 2026",
    "obligationAmount": 32470.94,
    "disbursementDate": "Mar 12, 2026",
    "disbursementAmount": 32470.94,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 31,
    "obligationNumber": "03-104-369-2026-03-00177 Current",
    "pap": "BICPPHE",
    "payee": "MANILA WATER",
    "particulars": "Payment for Manila Water under Contract Account No. 17158488 for the period of February 7,2026-March 6,2026.",
    "obligationDate": "Mar 12, 2026",
    "obligationAmount": 5115.86,
    "disbursementDate": "Mar 19, 2026",
    "disbursementAmount": 5115.86,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 32,
    "obligationNumber": "03-104-369-2026-03-00184 Current",
    "pap": "BICPPHE",
    "payee": "ARMIE O. BUNAG",
    "particulars": "To obligate the amount for the procurement of other supplies and materials to be used for the activity Leading Internalization: Strengthening Institutional Capacity and Canada-Philippines Linkages for the period of March 2-6,2026.",
    "obligationDate": "Mar 17, 2026",
    "obligationAmount": 9143,
    "disbursementDate": "Mar 26, 2026",
    "disbursementAmount": 9143,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 33,
    "obligationNumber": "03-104-369-2026-03-00202 Current",
    "pap": "BICPPHE",
    "payee": "BUREAU OF TREASURY-NCR",
    "particulars": "Payment of Fidelity Bond Premium of Ms.Mabel A. Gutierrez",
    "obligationDate": "Mar 19, 2026",
    "obligationAmount": 1125,
    "disbursementDate": "Mar 24, 2026",
    "disbursementAmount": 1125,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 34,
    "obligationNumber": "03-104-369-2026-03-00233 Current",
    "pap": "BICPPHE",
    "payee": "MABEL A. GUTIERREZ",
    "particulars": "Replenishment of petty cash fund.",
    "obligationDate": "Mar 30, 2026",
    "obligationAmount": 70000,
    "disbursementDate": "Mar 31, 2026",
    "disbursementAmount": 70000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 35,
    "obligationNumber": "03-104-369-2026-04-00273 Current",
    "pap": "BICPPHE",
    "payee": "MERALCO",
    "particulars": "Payment of Electric Consumption for the period of February 25,2026 to March 24,2026.",
    "obligationDate": "Apr 7, 2026",
    "obligationAmount": 32501.75,
    "disbursementDate": "Apr 8, 2026",
    "disbursementAmount": 32501.75,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 36,
    "obligationNumber": "03-104-369-2026-04-00317 Current",
    "pap": "BICPPHE",
    "payee": "JESUSA ROCEL S. ESTANISLAO",
    "particulars": "Reimbursement of other supplies and materials expenses incurred during the Planning and Preparatory Meeting with Education Malaysia Global Services and International Partners for the ASEAN GEMS Plus Initiatives for the period of March 9-12, 2026.",
    "obligationDate": "Apr 8, 2026",
    "obligationAmount": 926,
    "disbursementDate": "Apr 28, 2026",
    "disbursementAmount": 926,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 37,
    "obligationNumber": "03-104-369-2026-04-00393 Current",
    "pap": "BICPPHE",
    "payee": "ARMIE O. BUNAG",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS III",
    "obligationDate": "Apr 14, 2026",
    "obligationAmount": 581234.4,
    "disbursementDate": "Apr 21, 2026",
    "disbursementAmount": 125117.88,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 38,
    "obligationNumber": "03-104-369-2026-04-00394 Current",
    "pap": "BICPPHE",
    "payee": "PAULINE C. REYES",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS III",
    "obligationDate": "Apr 14, 2026",
    "obligationAmount": 581234.4,
    "disbursementDate": "Apr 21, 2026",
    "disbursementAmount": 127627.08,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 39,
    "obligationNumber": "03-104-369-2026-04-00395 Current",
    "pap": "BICPPHE",
    "payee": "MARICEL N. ERMITA",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS II",
    "obligationDate": "Apr 14, 2026",
    "obligationAmount": 455522.4,
    "disbursementDate": "Apr 21, 2026",
    "disbursementAmount": 96624.01,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 40,
    "obligationNumber": "03-104-369-2026-04-00396 Current",
    "pap": "BICPPHE",
    "payee": "ELDRIN DELGADO",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS II",
    "obligationDate": "Apr 14, 2026",
    "obligationAmount": 455522.4,
    "disbursementDate": "Apr 21, 2026",
    "disbursementAmount": 96537.79,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 41,
    "obligationNumber": "03-104-369-2026-04-00397 Current",
    "pap": "BICPPHE",
    "payee": "NERISSA MARIE H. GONO CRUZ",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS II",
    "obligationDate": "Apr 14, 2026",
    "obligationAmount": 455522.4,
    "disbursementDate": "May 11, 2026",
    "disbursementAmount": 71007.09,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 42,
    "obligationNumber": "03-104-369-2026-04-00398 Current",
    "pap": "BICPPHE",
    "payee": "DANNA MARIE H. SISTER",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS II",
    "obligationDate": "Apr 14, 2026",
    "obligationAmount": 455522.4,
    "disbursementDate": "Apr 21, 2026",
    "disbursementAmount": 101227.2,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 43,
    "obligationNumber": "03-104-369-2026-04-00399 Current",
    "pap": "BICPPHE",
    "payee": "JULES MARIEL S. MARTIN",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS I",
    "obligationDate": "Apr 14, 2026",
    "obligationAmount": 366627.6,
    "disbursementDate": "Apr 21, 2026",
    "disbursementAmount": 77319.44,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 44,
    "obligationNumber": "03-104-369-2026-04-00400 Current",
    "pap": "BICPPHE",
    "payee": "JAVEE A. TENORIA",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS I",
    "obligationDate": "Apr 14, 2026",
    "obligationAmount": 366627.6,
    "disbursementDate": "Apr 21, 2026",
    "disbursementAmount": 78600.96,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 45,
    "obligationNumber": "03-104-369-2026-04-00401 Current",
    "pap": "BICPPHE",
    "payee": "MA. SAMANTHA M. LUCIDO",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS I",
    "obligationDate": "Apr 14, 2026",
    "obligationAmount": 366627.6,
    "disbursementDate": "Apr 21, 2026",
    "disbursementAmount": 79156.8,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 46,
    "obligationNumber": "03-104-369-2026-04-00402 Current",
    "pap": "BICPPHE",
    "payee": "KIMBERLY O. DAYAWON",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS I",
    "obligationDate": "Apr 14, 2026",
    "obligationAmount": 366627.6,
    "disbursementDate": "Apr 21, 2026",
    "disbursementAmount": 81426.48,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 47,
    "obligationNumber": "03-104-369-2026-04-00403 Current",
    "pap": "BICPPHE",
    "payee": "SHERIE ANN N. CABANA",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS I",
    "obligationDate": "Apr 14, 2026",
    "obligationAmount": 366627.6,
    "disbursementDate": "Apr 21, 2026",
    "disbursementAmount": 72475.14,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 48,
    "obligationNumber": "03-104-369-2026-04-00404 Current",
    "pap": "BICPPHE",
    "payee": "DANIEL H. SABIANO",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PSS V",
    "obligationDate": "Apr 14, 2026",
    "obligationAmount": 290703.6,
    "disbursementDate": "Apr 21, 2026",
    "disbursementAmount": 61023.66,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 49,
    "obligationNumber": "03-104-369-2026-04-00405 Current",
    "pap": "BICPPHE",
    "payee": "JENNIFER P. CATUNGAL",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PSS V",
    "obligationDate": "Apr 14, 2026",
    "obligationAmount": 290703.6,
    "disbursementDate": "Apr 21, 2026",
    "disbursementAmount": 61684.62,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 50,
    "obligationNumber": "03-104-369-2026-04-00406 Current",
    "pap": "BICPPHE",
    "payee": "JULIA D. AGAPITO",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PSS IV",
    "obligationDate": "Apr 14, 2026",
    "obligationAmount": 262753.2,
    "disbursementDate": "Apr 16, 2026",
    "disbursementAmount": 13935,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 51,
    "obligationNumber": "03-104-369-2026-04-00426 Current",
    "pap": "BICPPHE",
    "payee": "JOSHUA KEN J. POLICARPIO",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS III",
    "obligationDate": "Apr 15, 2026",
    "obligationAmount": 581234.4,
    "disbursementDate": "Apr 21, 2026",
    "disbursementAmount": 95745.08,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 52,
    "obligationNumber": "03-104-369-2026-04-00427 Current",
    "pap": "BICPPHE",
    "payee": "PRINCE MICHAEL B. FUENTES",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS II",
    "obligationDate": "Apr 15, 2026",
    "obligationAmount": 455522.4,
    "disbursementDate": "Apr 8, 2026",
    "disbursementAmount": 103514.05,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 53,
    "obligationNumber": "03-104-369-2026-04-00433 Current",
    "pap": "BICPPHE",
    "payee": "MARY JANE L. YBANEZ",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS III",
    "obligationDate": "Apr 16, 2026",
    "obligationAmount": 581234.4,
    "disbursementDate": "Apr 23, 2026",
    "disbursementAmount": 126580.46,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 54,
    "obligationNumber": "03-104-369-2026-04-00434 Current",
    "pap": "BICPPHE",
    "payee": "AILENE B. FLORES",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS III",
    "obligationDate": "Apr 16, 2026",
    "obligationAmount": 581234.4,
    "disbursementDate": "Apr 23, 2026",
    "disbursementAmount": 124512,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 55,
    "obligationNumber": "03-104-369-2026-04-00435 Current",
    "pap": "BICPPHE",
    "payee": "ERICA E. EDER",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS II",
    "obligationDate": "Apr 16, 2026",
    "obligationAmount": 455522.4,
    "disbursementDate": "Apr 23, 2026",
    "disbursementAmount": 95196.59,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 56,
    "obligationNumber": "03-104-369-2026-04-00436 Current",
    "pap": "BICPPHE",
    "payee": "JAMES DARWIN N. LAGMAN",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS II",
    "obligationDate": "Apr 16, 2026",
    "obligationAmount": 455522.4,
    "disbursementDate": "Apr 23, 2026",
    "disbursementAmount": 101164.93,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 57,
    "obligationNumber": "03-104-369-2026-04-00437 Current",
    "pap": "BICPPHE",
    "payee": "KOTARO JNCYRL Q. VELASCO",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS II",
    "obligationDate": "Apr 16, 2026",
    "obligationAmount": 455522.4,
    "disbursementDate": "Apr 23, 2026",
    "disbursementAmount": 22432.8,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 58,
    "obligationNumber": "03-104-369-2026-04-00438 Current",
    "pap": "BICPPHE",
    "payee": "ACE C. VALENZUELA",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS II",
    "obligationDate": "Apr 16, 2026",
    "obligationAmount": 455522.4,
    "disbursementDate": "Apr 23, 2026",
    "disbursementAmount": 96236.02,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 59,
    "obligationNumber": "03-104-369-2026-04-00439 Current",
    "pap": "BICPPHE",
    "payee": "JOEYLYN R. SAGAT",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS I",
    "obligationDate": "Apr 16, 2026",
    "obligationAmount": 366627.6,
    "disbursementDate": "Apr 23, 2026",
    "disbursementAmount": 59424.66,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 60,
    "obligationNumber": "03-104-369-2026-04-00440 Current",
    "pap": "BICPPHE",
    "payee": "REGINE MAE H. GONZALES",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS I",
    "obligationDate": "Apr 16, 2026",
    "obligationAmount": 366627.6,
    "disbursementDate": "Apr 23, 2026",
    "disbursementAmount": 80392,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 61,
    "obligationNumber": "03-104-369-2026-04-00441 Current",
    "pap": "BICPPHE",
    "payee": "JAYVIE ANN C. BERMUDEZ",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PSS IV",
    "obligationDate": "Apr 16, 2026",
    "obligationAmount": 262753.2,
    "disbursementDate": "Apr 23, 2026",
    "disbursementAmount": 55063.8,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 62,
    "obligationNumber": "03-104-369-2026-04-00442 Current",
    "pap": "BICPPHE",
    "payee": "MA. ANGELA J. BAJET",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PSS IV",
    "obligationDate": "Apr 16, 2026",
    "obligationAmount": 262753.2,
    "disbursementDate": "Apr 23, 2026",
    "disbursementAmount": 44622.72,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 63,
    "obligationNumber": "03-104-369-2026-04-00446 Current",
    "pap": "BICPPHE",
    "payee": "CHRISTINE N. FERRER",
    "particulars": "Reimbursement of expenses incurred during the Preparatory Meeting with Education Malaysia Global Services(PEGS) for the period of March 11,2026.",
    "obligationDate": "Apr 20, 2026",
    "obligationAmount": 23700,
    "disbursementDate": "Apr 27, 2026",
    "disbursementAmount": 23700,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 64,
    "obligationNumber": "03-104-369-2026-04-00447 Current",
    "pap": "BICPPHE",
    "payee": "CHRISTINE N. FERRER",
    "particulars": "Reimbursement of travel expenses incurred during the Planning and Preparatory Meeting with Education Malaysia Global Services and International Partners for the ASEAN GEMS Plus Initiative for the period of March 9-12,2026.",
    "obligationDate": "Apr 20, 2026",
    "obligationAmount": 1500,
    "disbursementDate": "Apr 28, 2026",
    "disbursementAmount": 1500,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 65,
    "obligationNumber": "03-104-369-2026-04-00451 Current",
    "pap": "BICPPHE",
    "payee": "MANILA WATER",
    "particulars": "Payment of Manila Water under contract account no. 17158488 for the period of March 7,2026 to April 6,2026.",
    "obligationDate": "Apr 20, 2026",
    "obligationAmount": 3443.25,
    "disbursementDate": "Apr 22, 2026",
    "disbursementAmount": 3443.25,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 66,
    "obligationNumber": "03-104-369-2026-04-00462 Current",
    "pap": "BICPPHE",
    "payee": "VALOIS CATERING SERVICES",
    "particulars": "Payment for the food incurred during the Signing Ceremony and Benchmarking Visit of the Ministry of Health and Family Welfare with the Commission on Higher Education,Department of Foreign Affairs, UP Manila and The Philippine General Hospital at 2F CHED Auditorium for the period of April 1,2026.",
    "obligationDate": "Apr 22, 2026",
    "obligationAmount": 17500,
    "disbursementDate": "Apr 29, 2026",
    "disbursementAmount": 17500,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 67,
    "obligationNumber": "03-104-369-2026-04-00464 Current",
    "pap": "BICPPHE",
    "payee": "VALOIS CATERING SERVICES",
    "particulars": "Payment for the food incurred during the Courtesy Meeting of CHED IAS with the Taipei Economic and Cultural Office at 2F IAS Conference Room for the period of March 24,2026.",
    "obligationDate": "Apr 22, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Apr 29, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 68,
    "obligationNumber": "03-104-369-2026-04-00471 Current",
    "pap": "BICPPHE",
    "payee": "AMIHAN APRIL ALCAZAR",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 16,2026 via online.",
    "obligationDate": "Apr 22, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 69,
    "obligationNumber": "03-104-369-2026-04-00471 Current",
    "pap": "BICPPHE",
    "payee": "MARIBETH BUENVIAJE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 16,2026 via online.",
    "obligationDate": "Apr 22, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 70,
    "obligationNumber": "03-104-369-2026-04-00471 Current",
    "pap": "BICPPHE",
    "payee": "ROSETTE EIRA E. CAMUS",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 16,2026 via online.",
    "obligationDate": "Apr 22, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 71,
    "obligationNumber": "03-104-369-2026-04-00471 Current",
    "pap": "BICPPHE",
    "payee": "MILDRED CRISOSTOMO",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 16,2026 via online.",
    "obligationDate": "Apr 22, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 72,
    "obligationNumber": "03-104-369-2026-04-00471 Current",
    "pap": "BICPPHE",
    "payee": "FELINA ESPIQUE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 16,2026 via online.",
    "obligationDate": "Apr 22, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 73,
    "obligationNumber": "03-104-369-2026-04-00471 Current",
    "pap": "BICPPHE",
    "payee": "ERWIN M. FALLER",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 16,2026 via online.",
    "obligationDate": "Apr 22, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 74,
    "obligationNumber": "03-104-369-2026-04-00471 Current",
    "pap": "BICPPHE",
    "payee": "JEREMY MORALES",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 16,2026 via online.",
    "obligationDate": "Apr 22, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 75,
    "obligationNumber": "03-104-369-2026-04-00471 Current",
    "pap": "BICPPHE",
    "payee": "NESTOR ONG",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 16,2026 via online.",
    "obligationDate": "Apr 22, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 76,
    "obligationNumber": "03-104-369-2026-04-00471 Current",
    "pap": "BICPPHE",
    "payee": "JEROME DUQUE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 16,2026 via online.",
    "obligationDate": "Apr 22, 2026",
    "obligationAmount": 3000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 3000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 77,
    "obligationNumber": "03-104-369-2026-04-00472 Current",
    "pap": "BICPPHE",
    "payee": "MABEL A. GUTIERREZ",
    "particulars": "Payment for the UMAP Membership 2026",
    "obligationDate": "Apr 22, 2026",
    "obligationAmount": 795.15,
    "disbursementDate": "Apr 28, 2026",
    "disbursementAmount": 795.15,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 78,
    "obligationNumber": "03-104-369-2026-04-00475 Current",
    "pap": "BICPPHE",
    "payee": "NINO SATHUR FIRME",
    "particulars": "COS' Salaries - April 1 - December 31, 2026 - PTS II",
    "obligationDate": "Apr 22, 2026",
    "obligationAmount": 455522.4,
    "disbursementDate": "May 13, 2026",
    "disbursementAmount": 99862.05,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 79,
    "obligationNumber": "03-104-369-2026-04-00483 Current",
    "pap": "BICPPHE",
    "payee": "MARIANO MARCOS STATE UNIVERSITY",
    "particulars": "Payment for the conduct of PHASE 3 out of the 3 PHASES of the Monitoring and Mapping of Philippine HEIs SDG Initiatives.",
    "obligationDate": "Apr 27, 2026",
    "obligationAmount": 10420830,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 80,
    "obligationNumber": "03-104-369-2026-04-00486 Current",
    "pap": "BICPPHE",
    "payee": "JESUSA ROCEL S. ESTANISLAO",
    "particulars": "Reimbursement of supplies and materials expenses incurred during the Planning and Preparatory Meeting with Education Malaysia Global Services and International Partners for the ASEAN GEMS Plus Initiatives for the period of March 9-12,2026.",
    "obligationDate": "Apr 27, 2026",
    "obligationAmount": 13116.2,
    "disbursementDate": "Apr 29, 2026",
    "disbursementAmount": 13116.2,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 81,
    "obligationNumber": "03-104-369-2026-04-00488 Current",
    "pap": "BICPPHE",
    "payee": "JESUSA ROCEL S. ESTANISLAO",
    "particulars": "Reimbursement for the gasoline and toll fee to attend the rehearsal for the MOU signing with Bangladesh to be conducted by the DFA Office of Protocol in DFA Office,Double Dragon Towers Pasay City for the period of March 25,2026.",
    "obligationDate": "Apr 27, 2026",
    "obligationAmount": 1264,
    "disbursementDate": "May 19, 2026",
    "disbursementAmount": 1264,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 82,
    "obligationNumber": "03-104-369-2026-04-00491 Current",
    "pap": "BICPPHE",
    "payee": "AMIHAN APRIL ALCAZAR",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 23,2026 via Zoom online.",
    "obligationDate": "Apr 27, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 83,
    "obligationNumber": "03-104-369-2026-04-00491 Current",
    "pap": "BICPPHE",
    "payee": "MARIBETH BUENVIAJE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 23,2026 via Zoom online.",
    "obligationDate": "Apr 27, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 84,
    "obligationNumber": "03-104-369-2026-04-00491 Current",
    "pap": "BICPPHE",
    "payee": "ROSETTE EIRA E. CAMUS",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 23,2026 via Zoom online.",
    "obligationDate": "Apr 27, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 85,
    "obligationNumber": "03-104-369-2026-04-00491 Current",
    "pap": "BICPPHE",
    "payee": "MILDRED CRISOSTOMO",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 23,2026 via Zoom online.",
    "obligationDate": "Apr 27, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 86,
    "obligationNumber": "03-104-369-2026-04-00491 Current",
    "pap": "BICPPHE",
    "payee": "FELINA ESPIQUE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 23,2026 via Zoom online.",
    "obligationDate": "Apr 27, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 87,
    "obligationNumber": "03-104-369-2026-04-00491 Current",
    "pap": "BICPPHE",
    "payee": "ERWIN M. FALLER",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 23,2026 via Zoom online.",
    "obligationDate": "Apr 27, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 88,
    "obligationNumber": "03-104-369-2026-04-00491 Current",
    "pap": "BICPPHE",
    "payee": "JEREMY MORALES",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 23,2026 via Zoom online.",
    "obligationDate": "Apr 27, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 89,
    "obligationNumber": "03-104-369-2026-04-00491 Current",
    "pap": "BICPPHE",
    "payee": "NESTOR ONG",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 23,2026 via Zoom online.",
    "obligationDate": "Apr 27, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 90,
    "obligationNumber": "03-104-369-2026-04-00491 Current",
    "pap": "BICPPHE",
    "payee": "RODOLFO RUDY SABAS",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 23,2026 via Zoom online.",
    "obligationDate": "Apr 27, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 91,
    "obligationNumber": "03-104-369-2026-04-00491 Current",
    "pap": "BICPPHE",
    "payee": "JEROME DUQUE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of March 23,2026 via Zoom online.",
    "obligationDate": "Apr 27, 2026",
    "obligationAmount": 3000,
    "disbursementDate": "Jun 8, 2026",
    "disbursementAmount": 3000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 92,
    "obligationNumber": "03-104-369-2026-04-00517 Current",
    "pap": "BICPPHE",
    "payee": "AMIHAN APRIL ALCAZAR",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 15,2026 via Zoom.",
    "obligationDate": "Apr 29, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 9, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 93,
    "obligationNumber": "03-104-369-2026-04-00517 Current",
    "pap": "BICPPHE",
    "payee": "MARIBETH BUENVIAJE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 15,2026 via Zoom.",
    "obligationDate": "Apr 29, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 9, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 94,
    "obligationNumber": "03-104-369-2026-04-00517 Current",
    "pap": "BICPPHE",
    "payee": "ROSETTE EIRA E. CAMUS",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 15,2026 via Zoom.",
    "obligationDate": "Apr 29, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 9, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 95,
    "obligationNumber": "03-104-369-2026-04-00517 Current",
    "pap": "BICPPHE",
    "payee": "MILDRED CRISOSTOMO",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 15,2026 via Zoom.",
    "obligationDate": "Apr 29, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 9, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 96,
    "obligationNumber": "03-104-369-2026-04-00517 Current",
    "pap": "BICPPHE",
    "payee": "FELINA ESPIQUE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 15,2026 via Zoom.",
    "obligationDate": "Apr 29, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 9, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 97,
    "obligationNumber": "03-104-369-2026-04-00517 Current",
    "pap": "BICPPHE",
    "payee": "ERWIN M. FALLER",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 15,2026 via Zoom.",
    "obligationDate": "Apr 29, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 9, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 98,
    "obligationNumber": "03-104-369-2026-04-00517 Current",
    "pap": "BICPPHE",
    "payee": "JEREMY MORALES",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 15,2026 via Zoom.",
    "obligationDate": "Apr 29, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 9, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 99,
    "obligationNumber": "03-104-369-2026-04-00517 Current",
    "pap": "BICPPHE",
    "payee": "NESTOR ONG",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 15,2026 via Zoom.",
    "obligationDate": "Apr 29, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "Jun 9, 2026",
    "disbursementAmount": 5000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 100,
    "obligationNumber": "03-104-369-2026-04-00517 Current",
    "pap": "BICPPHE",
    "payee": "JEROME DUQUE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 15,2026 via Zoom.",
    "obligationDate": "Apr 29, 2026",
    "obligationAmount": 3000,
    "disbursementDate": "Jun 9, 2026",
    "disbursementAmount": 3000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 101,
    "obligationNumber": "03-104-369-2026-04-00517 Current",
    "pap": "BICPPHE",
    "payee": "BEEJAY SEBASTIAN",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 15,2026 via Zoom.",
    "obligationDate": "Apr 29, 2026",
    "obligationAmount": 3000,
    "disbursementDate": "Jun 9, 2026",
    "disbursementAmount": 3000,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 102,
    "obligationNumber": "03-104-369-2026-05-00538 Current",
    "pap": "BICPPHE",
    "payee": "MICHELLE A. ONG",
    "particulars": "Payment of cash advance for participation in the Deep Dialogues 2026 in the United Kingdom for the period of May 4-9,2026.",
    "obligationDate": "May 4, 2026",
    "obligationAmount": 71514.45,
    "disbursementDate": "May 5, 2026",
    "disbursementAmount": 71514.45,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 103,
    "obligationNumber": "03-104-369-2026-05-00554 Current",
    "pap": "BICPPHE",
    "payee": "VALOIS CATERING SERVICES",
    "particulars": "Payment for the food incurred during the State Universities and Colleges(SUCs) System Presentation at 2F IAS Conference Room for the period of April 21,2026.",
    "obligationDate": "May 5, 2026",
    "obligationAmount": 3500,
    "disbursementDate": "May 14, 2026",
    "disbursementAmount": 3500,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 104,
    "obligationNumber": "03-104-369-2026-05-00556 Current",
    "pap": "BICPPHE",
    "payee": "MERALCO",
    "particulars": "Payment of Electric consumption for the period of March 25,2026 to April 24,2026.",
    "obligationDate": "May 6, 2026",
    "obligationAmount": 34656.4,
    "disbursementDate": "May 7, 2026",
    "disbursementAmount": 34656.4,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 105,
    "obligationNumber": "03-104-369-2026-05-00578 Current",
    "pap": "BICPPHE",
    "payee": "AMIHAN APRIL ALCAZAR",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 22,2026 via Zoom.",
    "obligationDate": "May 7, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 106,
    "obligationNumber": "03-104-369-2026-05-00578 Current",
    "pap": "BICPPHE",
    "payee": "MARIBETH BUENVIAJE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 22,2026 via Zoom.",
    "obligationDate": "May 7, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 107,
    "obligationNumber": "03-104-369-2026-05-00578 Current",
    "pap": "BICPPHE",
    "payee": "ROSETTE EIRA E. CAMUS",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 22,2026 via Zoom.",
    "obligationDate": "May 7, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 108,
    "obligationNumber": "03-104-369-2026-05-00578 Current",
    "pap": "BICPPHE",
    "payee": "MILDRED CRISOSTOMO",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 22,2026 via Zoom.",
    "obligationDate": "May 7, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 109,
    "obligationNumber": "03-104-369-2026-05-00578 Current",
    "pap": "BICPPHE",
    "payee": "FELINA ESPIQUE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 22,2026 via Zoom.",
    "obligationDate": "May 7, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 110,
    "obligationNumber": "03-104-369-2026-05-00578 Current",
    "pap": "BICPPHE",
    "payee": "ERWIN M. FALLER",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 22,2026 via Zoom.",
    "obligationDate": "May 7, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 111,
    "obligationNumber": "03-104-369-2026-05-00578 Current",
    "pap": "BICPPHE",
    "payee": "JEROME DUQUE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 22,2026 via Zoom.",
    "obligationDate": "May 7, 2026",
    "obligationAmount": 3000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 112,
    "obligationNumber": "03-104-369-2026-05-00578 Current",
    "pap": "BICPPHE",
    "payee": "BEEJAY SEBASTIAN",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 22,2026 via Zoom.",
    "obligationDate": "May 7, 2026",
    "obligationAmount": 3000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 113,
    "obligationNumber": "03-104-369-2026-05-00593 Current",
    "pap": "BICPPHE",
    "payee": "MQN OFFICE AND SCHOOL SUPPLIES TRADING",
    "particulars": "Procurement of Original/Genuine EPSON Ink 003 for the use of office",
    "obligationDate": "May 7, 2026",
    "obligationAmount": 97175,
    "disbursementDate": "Jun 10, 2026",
    "disbursementAmount": 97175,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 114,
    "obligationNumber": "03-104-369-2026-05-00594 Current",
    "pap": "BICPPHE",
    "payee": "ES PRINT MEDIA INC.",
    "particulars": "Procurement of ink tank printer(print only) with A3+ capability for the use of office",
    "obligationDate": "May 7, 2026",
    "obligationAmount": 29545,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 115,
    "obligationNumber": "03-104-369-2026-05-00597 Current",
    "pap": "BICPPHE",
    "payee": "JESUSA ROCEL S. ESTANISLAO",
    "particulars": "Reimbursement of expenses incurred during the Planning and Preparatory Meeting with Education Malaysia Global Services and International Partners for the ASEAN GEMS plus Initiatives for the period of March 9-12,2026.",
    "obligationDate": "May 11, 2026",
    "obligationAmount": 2100,
    "disbursementDate": "Jun 3, 2026",
    "disbursementAmount": 2100,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 116,
    "obligationNumber": "03-104-369-2026-05-00597 Current",
    "pap": "BICPPHE",
    "payee": "MA. CELINA A. MARINO",
    "particulars": "Reimbursement of expenses incurred during the Planning and Preparatory Meeting with Education Malaysia Global Services and International Partners for the ASEAN GEMS plus Initiatives for the period of March 9-12,2026.",
    "obligationDate": "May 11, 2026",
    "obligationAmount": 2100,
    "disbursementDate": "Jun 3, 2026",
    "disbursementAmount": 2100,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 117,
    "obligationNumber": "03-104-369-2026-05-00597 Current",
    "pap": "BICPPHE",
    "payee": "EDNALYN GRACE VISTE",
    "particulars": "Reimbursement of expenses incurred during the Planning and Preparatory Meeting with Education Malaysia Global Services and International Partners for the ASEAN GEMS plus Initiatives for the period of March 9-12,2026.",
    "obligationDate": "May 11, 2026",
    "obligationAmount": 1500,
    "disbursementDate": "Jun 3, 2026",
    "disbursementAmount": 1500,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 118,
    "obligationNumber": "03-104-369-2026-05-00597 Current",
    "pap": "BICPPHE",
    "payee": "JOSHUA KEN J. POLICARPIO",
    "particulars": "Reimbursement of expenses incurred during the Planning and Preparatory Meeting with Education Malaysia Global Services and International Partners for the ASEAN GEMS plus Initiatives for the period of March 9-12,2026.",
    "obligationDate": "May 11, 2026",
    "obligationAmount": 2100,
    "disbursementDate": "Jun 3, 2026",
    "disbursementAmount": 2100,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 119,
    "obligationNumber": "03-104-369-2026-05-00597 Current",
    "pap": "BICPPHE",
    "payee": "JAMES DARWIN N. LAGMAN",
    "particulars": "Reimbursement of expenses incurred during the Planning and Preparatory Meeting with Education Malaysia Global Services and International Partners for the ASEAN GEMS plus Initiatives for the period of March 9-12,2026.",
    "obligationDate": "May 11, 2026",
    "obligationAmount": 2100,
    "disbursementDate": "Jun 3, 2026",
    "disbursementAmount": 2100,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 120,
    "obligationNumber": "03-104-369-2026-05-00597 Current",
    "pap": "BICPPHE",
    "payee": "JOEYLYN R. SAGAT",
    "particulars": "Reimbursement of expenses incurred during the Planning and Preparatory Meeting with Education Malaysia Global Services and International Partners for the ASEAN GEMS plus Initiatives for the period of March 9-12,2026.",
    "obligationDate": "May 11, 2026",
    "obligationAmount": 2100,
    "disbursementDate": "Jun 3, 2026",
    "disbursementAmount": 2100,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 121,
    "obligationNumber": "03-104-369-2026-05-00597 Current",
    "pap": "BICPPHE",
    "payee": "REGINE MAE H. GONZALES",
    "particulars": "Reimbursement of expenses incurred during the Planning and Preparatory Meeting with Education Malaysia Global Services and International Partners for the ASEAN GEMS plus Initiatives for the period of March 9-12,2026.",
    "obligationDate": "May 11, 2026",
    "obligationAmount": 2100,
    "disbursementDate": "Jun 3, 2026",
    "disbursementAmount": 2100,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 122,
    "obligationNumber": "03-104-369-2026-05-00597 Current",
    "pap": "BICPPHE",
    "payee": "DANIEL H. SABIANO",
    "particulars": "Reimbursement of expenses incurred during the Planning and Preparatory Meeting with Education Malaysia Global Services and International Partners for the ASEAN GEMS plus Initiatives for the period of March 9-12,2026.",
    "obligationDate": "May 11, 2026",
    "obligationAmount": 2100,
    "disbursementDate": "Jun 3, 2026",
    "disbursementAmount": 2100,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 123,
    "obligationNumber": "03-104-369-2026-05-00597 Current",
    "pap": "BICPPHE",
    "payee": "EUGENIO CAGASCO",
    "particulars": "Reimbursement of expenses incurred during the Planning and Preparatory Meeting with Education Malaysia Global Services and International Partners for the ASEAN GEMS plus Initiatives for the period of March 9-12,2026.",
    "obligationDate": "May 11, 2026",
    "obligationAmount": 2100,
    "disbursementDate": "Jun 3, 2026",
    "disbursementAmount": 2100,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 124,
    "obligationNumber": "03-104-369-2026-05-00599 Current",
    "pap": "BICPPHE",
    "payee": "JESUSA ROCEL S. ESTANISLAO",
    "particulars": "Reimbursement for the advocacy materials/other supplies and materials incurred during the Signing Ceremony and Benchmarking visit of the Ministry of Health and Family Welfare with the Commission on Higher Education,Department of Foreign Affairs,UP Manila and The Philippine General Hospital for the period of April 1,2026.",
    "obligationDate": "May 12, 2026",
    "obligationAmount": 9380,
    "disbursementDate": "May 26, 2026",
    "disbursementAmount": 9380,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 125,
    "obligationNumber": "03-104-369-2026-05-00607 Current",
    "pap": "BICPPHE",
    "payee": "CHRISTINE N. FERRER",
    "particulars": "Reimbursement of travel expenses incurred during the Justice through Science: Advancing Forensic Science Education for a More Orderly, Secure, and Progressive Philippines for the period of April 15-17,2026 in Baguio City.",
    "obligationDate": "May 13, 2026",
    "obligationAmount": 17331.45,
    "disbursementDate": "May 20, 2026",
    "disbursementAmount": 17331.45,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 126,
    "obligationNumber": "03-104-369-2026-05-00609 Current",
    "pap": "BICPPHE",
    "payee": "CHRISTINE N. FERRER",
    "particulars": "Payment for cash advance to participate in the Education World Forum (EWF) 2026 in London, United Kingdom on May 14-24, 2026.",
    "obligationDate": "May 13, 2026",
    "obligationAmount": 174492.8,
    "disbursementDate": "May 13, 2026",
    "disbursementAmount": 174492.8,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 127,
    "obligationNumber": "03-104-369-2026-05-00615 Current",
    "pap": "BICPPHE",
    "payee": "SHIRLEY C. AGRUPIS",
    "particulars": "Payment for cash advance to participate in the Education World Forum (EWF) 2026 in London, United Kingdom on May 14-24, 2026.",
    "obligationDate": "May 13, 2026",
    "obligationAmount": 174189.1,
    "disbursementDate": "May 14, 2026",
    "disbursementAmount": 174189.1,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 128,
    "obligationNumber": "03-104-369-2026-05-00618 Current",
    "pap": "BICPPHE",
    "payee": "NOREEN V. DE VERA",
    "particulars": "COS' Salaries - May 4 - December 31, 2026 - PTS I",
    "obligationDate": "May 14, 2026",
    "obligationAmount": 321948.97,
    "disbursementDate": "Jun 4, 2026",
    "disbursementAmount": 36794.17,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 129,
    "obligationNumber": "03-104-369-2026-05-00619 Current",
    "pap": "BICPPHE",
    "payee": "MANILA WATER",
    "particulars": "Payment of Manila Water under Contract Account No. 17158488 for the period of April 7,2026 to May 6,2026.",
    "obligationDate": "May 14, 2026",
    "obligationAmount": 3937.7,
    "disbursementDate": "May 14, 2026",
    "disbursementAmount": 3937.7,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 130,
    "obligationNumber": "03-104-369-2026-05-00620 Current",
    "pap": "BICPPHE",
    "payee": "GUILBERT A. GANZAN",
    "particulars": "Reimbursement of travel expenses incurred during the Justice through Science: Advancing Forensic Science Education for a More Orderly, Secure, and Progressive Philippines for the period of April 15-17,2026 in Baguio City.",
    "obligationDate": "May 14, 2026",
    "obligationAmount": 4020,
    "disbursementDate": "May 20, 2026",
    "disbursementAmount": 4020,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 131,
    "obligationNumber": "03-104-369-2026-05-00637 Current",
    "pap": "BICPPHE",
    "payee": "AMIHAN APRIL ALCAZAR",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 29,2026 via Zoom.",
    "obligationDate": "May 18, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 132,
    "obligationNumber": "03-104-369-2026-05-00637 Current",
    "pap": "BICPPHE",
    "payee": "MARIBETH BUENVIAJE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 29,2026 via Zoom.",
    "obligationDate": "May 18, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 133,
    "obligationNumber": "03-104-369-2026-05-00637 Current",
    "pap": "BICPPHE",
    "payee": "MILDRED CRISOSTOMO",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 29,2026 via Zoom.",
    "obligationDate": "May 18, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 134,
    "obligationNumber": "03-104-369-2026-05-00637 Current",
    "pap": "BICPPHE",
    "payee": "JEREMY MORALES",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 29,2026 via Zoom.",
    "obligationDate": "May 18, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 135,
    "obligationNumber": "03-104-369-2026-05-00637 Current",
    "pap": "BICPPHE",
    "payee": "RODOLFO RUDY SABAS",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 29,2026 via Zoom.",
    "obligationDate": "May 18, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 136,
    "obligationNumber": "03-104-369-2026-05-00637 Current",
    "pap": "BICPPHE",
    "payee": "JEROME DUQUE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the Meeting of the National Review Committee on CHED-Funded Internationalization Programs for the period of April 29,2026 via Zoom.",
    "obligationDate": "May 18, 2026",
    "obligationAmount": 3000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 137,
    "obligationNumber": "03-104-369-2026-05-00648 Current",
    "pap": "BICPPHE",
    "payee": "ALINE MAGALONG",
    "particulars": "Payment for cash advance to participate in the ASEAN-China SME Trade and Investment Facilitation Training Program and the 2026 RCEP Local Governments and Friendship Cities Cooperation(Huangshan) Forum, held in Hefei and Huangshan, Anhui Province,China for the period of May 24-30,2026.",
    "obligationDate": "May 19, 2026",
    "obligationAmount": 63188.85,
    "disbursementDate": "May 20, 2026",
    "disbursementAmount": 63188.85,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 138,
    "obligationNumber": "03-104-369-2026-05-00693 Current",
    "pap": "BICPPHE",
    "payee": "MARIO N. DOMINGO, JR.",
    "particulars": "COS' Salaries - May 4,2026 to December 31, 2026 - PSS IV",
    "obligationDate": "May 26, 2026",
    "obligationAmount": 230733.1,
    "disbursementDate": "Jun 4, 2026",
    "disbursementAmount": 26369.49,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 139,
    "obligationNumber": "03-104-369-2026-05-00708 Current",
    "pap": "BICPPHE",
    "payee": "LANDBANK OF THE PHILIPPINES",
    "particulars": "Reimbursement of airfare expenses incurred during the Planning and Preparatory Meeting with Education Malaysia Global Services and International Partners for the ASEAN GEMS Plus Initiatives at Clark, Pampanga for the period of March 9-12,2026.",
    "obligationDate": "May 28, 2026",
    "obligationAmount": 32454.64,
    "disbursementDate": "Jun 2, 2026",
    "disbursementAmount": 32454.64,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 140,
    "obligationNumber": "03-104-369-2026-05-00709 Current",
    "pap": "BICPPHE",
    "payee": "LANDBANK OF THE PHILIPPINES",
    "particulars": "Reimbursement of airfare expenses incurred during the Planning and Preparatory Meeting with Education Malaysia Global Services and International Partners for the ASEAN GEMS Plus Initiatives at Clark, Pampanga for the period of March 9-12,2026.",
    "obligationDate": "May 28, 2026",
    "obligationAmount": 71815.35,
    "disbursementDate": "Jun 2, 2026",
    "disbursementAmount": 71815.35,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 141,
    "obligationNumber": "03-104-369-2026-05-00710 Current",
    "pap": "BICPPHE",
    "payee": "HANN PHILIPPINES, INC. (CLARK MARRIOTT HOTEL)",
    "particulars": "Payment of food and accomodation expenses incurred during the Planning and Preparatory Meeting with Education Malaysia Global Services and International Partners for the ASEAN GEMS Plus Initiatives for the period of March 9-12,2026.",
    "obligationDate": "May 28, 2026",
    "obligationAmount": 25269.54,
    "disbursementDate": "Jun 3, 2026",
    "disbursementAmount": 25269.54,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 142,
    "obligationNumber": "03-104-369-2026-06-00738 Current",
    "pap": "BICPPHE",
    "payee": "MABEL A. GUTIERREZ",
    "particulars": "Replenish the amount incurred and disbursed from the petty cash fund.",
    "obligationDate": "Jun 1, 2026",
    "obligationAmount": 53407.7,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 143,
    "obligationNumber": "03-104-369-2026-06-00746 Current",
    "pap": "BICPPHE",
    "payee": "VALOIS CATERING SERVICES",
    "particulars": "Payment for the food incurred during the Courtesy Meeting of UMAP Board of Directors with IAS Director and Representatives for the period of May 12,2026 at 2F IAS Conference Room.",
    "obligationDate": "Jun 1, 2026",
    "obligationAmount": 2100,
    "disbursementDate": "Jun 4, 2026",
    "disbursementAmount": 2100,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 144,
    "obligationNumber": "03-104-369-2026-06-00747 Current",
    "pap": "BICPPHE",
    "payee": "VALOIS CATERING SERVICES",
    "particulars": "Payment for the food incurred during the IZN Content Deliverables Presentation and Social Media Strategy Alignment meeting with Ms. Jing Castaneda and Team for the period of May 6,2026.",
    "obligationDate": "Jun 1, 2026",
    "obligationAmount": 3500,
    "disbursementDate": "Jun 4, 2026",
    "disbursementAmount": 3500,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 145,
    "obligationNumber": "03-104-369-2026-06-00783 Current",
    "pap": "BICPPHE",
    "payee": "MERALCO",
    "particulars": "Payment of Electric Consumption for the period of April 25,2026 to May 24,2026.",
    "obligationDate": "Jun 3, 2026",
    "obligationAmount": 59718.93,
    "disbursementDate": "Jun 4, 2026",
    "disbursementAmount": 59718.93,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 146,
    "obligationNumber": "03-104-369-2026-06-00784 Current",
    "pap": "BICPPHE",
    "payee": "MABEL A. GUTIERREZ",
    "particulars": "Reimbursement of representation expenses incurred during the FSTP Roadshows for the period of May 26,2026 in CHED Auditorium.",
    "obligationDate": "Jun 3, 2026",
    "obligationAmount": 145784.95,
    "disbursementDate": "Jun 4, 2026",
    "disbursementAmount": 145784.95,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 147,
    "obligationNumber": "03-104-369-2026-06-00793 Current",
    "pap": "BICPPHE",
    "payee": "MARIBETH BUENVIAJE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the meeting of the National Review Committee on CHED-Funded Internalization Programs for the period of May 6,2026 via Zoom(online)",
    "obligationDate": "Jun 4, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 148,
    "obligationNumber": "03-104-369-2026-06-00793 Current",
    "pap": "BICPPHE",
    "payee": "ROSETTE EIRA E. CAMUS",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the meeting of the National Review Committee on CHED-Funded Internalization Programs for the period of May 6,2026 via Zoom(online)",
    "obligationDate": "Jun 4, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 149,
    "obligationNumber": "03-104-369-2026-06-00793 Current",
    "pap": "BICPPHE",
    "payee": "MILDRED CRISOSTOMO",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the meeting of the National Review Committee on CHED-Funded Internalization Programs for the period of May 6,2026 via Zoom(online)",
    "obligationDate": "Jun 4, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 150,
    "obligationNumber": "03-104-369-2026-06-00793 Current",
    "pap": "BICPPHE",
    "payee": "ERWIN M. FALLER",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the meeting of the National Review Committee on CHED-Funded Internalization Programs for the period of May 6,2026 via Zoom(online)",
    "obligationDate": "Jun 4, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 151,
    "obligationNumber": "03-104-369-2026-06-00793 Current",
    "pap": "BICPPHE",
    "payee": "JEREMY MORALES",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the meeting of the National Review Committee on CHED-Funded Internalization Programs for the period of May 6,2026 via Zoom(online)",
    "obligationDate": "Jun 4, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 152,
    "obligationNumber": "03-104-369-2026-06-00793 Current",
    "pap": "BICPPHE",
    "payee": "NESTOR ONG",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the meeting of the National Review Committee on CHED-Funded Internalization Programs for the period of May 6,2026 via Zoom(online)",
    "obligationDate": "Jun 4, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 153,
    "obligationNumber": "03-104-369-2026-06-00793 Current",
    "pap": "BICPPHE",
    "payee": "RODOLFO RUDY SABAS",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the meeting of the National Review Committee on CHED-Funded Internalization Programs for the period of May 6,2026 via Zoom(online)",
    "obligationDate": "Jun 4, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 154,
    "obligationNumber": "03-104-369-2026-06-00793 Current",
    "pap": "BICPPHE",
    "payee": "JEROME DUQUE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the meeting of the National Review Committee on CHED-Funded Internalization Programs for the period of May 6,2026 via Zoom(online)",
    "obligationDate": "Jun 4, 2026",
    "obligationAmount": 3000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 155,
    "obligationNumber": "03-104-369-2026-06-00794 Current",
    "pap": "BICPPHE",
    "payee": "AMIHAN APRIL ALCAZAR",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the meeting of the National Review Committee on CHED-Funded Internalization Programs for the period of May 13,2026 via Zoom(online)",
    "obligationDate": "Jun 4, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 156,
    "obligationNumber": "03-104-369-2026-06-00794 Current",
    "pap": "BICPPHE",
    "payee": "MARIBETH BUENVIAJE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the meeting of the National Review Committee on CHED-Funded Internalization Programs for the period of May 13,2026 via Zoom(online)",
    "obligationDate": "Jun 4, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 157,
    "obligationNumber": "03-104-369-2026-06-00794 Current",
    "pap": "BICPPHE",
    "payee": "ROSETTE EIRA E. CAMUS",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the meeting of the National Review Committee on CHED-Funded Internalization Programs for the period of May 13,2026 via Zoom(online)",
    "obligationDate": "Jun 4, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 158,
    "obligationNumber": "03-104-369-2026-06-00794 Current",
    "pap": "BICPPHE",
    "payee": "MILDRED CRISOSTOMO",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the meeting of the National Review Committee on CHED-Funded Internalization Programs for the period of May 13,2026 via Zoom(online)",
    "obligationDate": "Jun 4, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 159,
    "obligationNumber": "03-104-369-2026-06-00794 Current",
    "pap": "BICPPHE",
    "payee": "FELINA ESPIQUE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the meeting of the National Review Committee on CHED-Funded Internalization Programs for the period of May 13,2026 via Zoom(online)",
    "obligationDate": "Jun 4, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 160,
    "obligationNumber": "03-104-369-2026-06-00794 Current",
    "pap": "BICPPHE",
    "payee": "ERWIN M. FALLER",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the meeting of the National Review Committee on CHED-Funded Internalization Programs for the period of May 13,2026 via Zoom(online)",
    "obligationDate": "Jun 4, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 161,
    "obligationNumber": "03-104-369-2026-06-00794 Current",
    "pap": "BICPPHE",
    "payee": "NESTOR ONG",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the meeting of the National Review Committee on CHED-Funded Internalization Programs for the period of May 13,2026 via Zoom(online)",
    "obligationDate": "Jun 4, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 162,
    "obligationNumber": "03-104-369-2026-06-00794 Current",
    "pap": "BICPPHE",
    "payee": "RODOLFO RUDY SABAS",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the meeting of the National Review Committee on CHED-Funded Internalization Programs for the period of May 13,2026 via Zoom(online)",
    "obligationDate": "Jun 4, 2026",
    "obligationAmount": 5000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 163,
    "obligationNumber": "03-104-369-2026-06-00794 Current",
    "pap": "BICPPHE",
    "payee": "JEROME DUQUE",
    "particulars": "Payment of honorarium for the services rendered during the conduct of the meeting of the National Review Committee on CHED-Funded Internalization Programs for the period of May 13,2026 via Zoom(online)",
    "obligationDate": "Jun 4, 2026",
    "obligationAmount": 3000,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 164,
    "obligationNumber": "03-104-369-2026-06-00809 Current",
    "pap": "BICPPHE",
    "payee": "METROTECH RENTAL SOLUTIONS, INC.",
    "particulars": "Payment of the procurement of service provider for the rental of LED Wall incurred during the Foreign Scholarships and Training Program (FSTP) Roadshow- NCR Leg for the period of May 26,2026 in CHED Auditorium.",
    "obligationDate": "Jun 9, 2026",
    "obligationAmount": 31024,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 165,
    "obligationNumber": "03-104-369-2026-06-00835 Current",
    "pap": "BICPPHE",
    "payee": "MABEL A. GUTIERREZ",
    "particulars": "Procurement of other supplies and materials used in the Education World Forum for the period of May 14-25,2026 in United Kingdom.",
    "obligationDate": "Jun 15, 2026",
    "obligationAmount": 10389,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 166,
    "obligationNumber": "03-104-369-2026-06-00840 Current",
    "pap": "BICPPHE",
    "payee": "MANILA WATER",
    "particulars": "Payment of Manila Water under contract account no. 17158488 for the period of May 7,2026 to June 6,2026.",
    "obligationDate": "Jun 15, 2026",
    "obligationAmount": 7448.64,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "",
    "subAllotmentAmount": 0,
    "type": "CURRENT"
  },
  {
    "id": 167,
    "obligationNumber": "CHEDRO-VII-2026-001 Continuing",
    "pap": "BICPPHE",
    "payee": "CHEDRO VII",
    "particulars": "Fund Transfer for the conduct of Leading Internationalization: Strengthening Institutional Capacity and Canada-Philippines Linkages on March 1-7, 2026.",
    "obligationDate": "",
    "obligationAmount": 0,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "Feb 27, 2026",
    "subAllotmentAmount": 23080,
    "type": "CONTINUING"
  },
  {
    "id": 168,
    "obligationNumber": "CHEDRO-X-2026-001 Continuing",
    "pap": "BICPPHE",
    "payee": "CHEDRO X",
    "particulars": "Fund Transfer for the conduct of Leading Internationalization: Strengthening Institutional Capacity and Canada-Philippines Linkages on March 1-7, 2026.",
    "obligationDate": "",
    "obligationAmount": 0,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "Feb 27, 2026",
    "subAllotmentAmount": 23160,
    "type": "CONTINUING"
  },
  {
    "id": 169,
    "obligationNumber": "CHEDRO-XII-2026-003 Continuing",
    "pap": "BICPPHE",
    "payee": "CHEDRO XII",
    "particulars": "Fund Transfer for then conduct of Leading Internationalization: Strengthening Institutional Capacity and Canada-Philippines Linkages on March 1-7, 2026.",
    "obligationDate": "",
    "obligationAmount": 0,
    "disbursementDate": "",
    "disbursementAmount": 0,
    "subAllotmentDate": "Mar 5, 2026",
    "subAllotmentAmount": 34700,
    "type": "CONTINUING"
  }
];
